baseURL: https://nedsec.org/
languageCode: en
title: nedsec.org

theme: ["PaperMod"]

languages:
    en:
        languageName: English
        weight: 1
        menu:
          main:
            - identifier: Archives
              name: Archives
              url: /archives/
              weight: 10
        homeInfoParams:
          Title: "Hi, I'm Ned"
          Content: "Iâ€™m an application security consultant with a background in cybersecurity, psychology, and geopolitics. I am fascinated by how people, systems, and threats interact in a complex global environment."
        socialIcons:
          - name: linkedin
            url: "https://www.linkedin.com/in/nedpfeiffer/"
          - name: github
            url: "https://github.com/nedpfeiffer/"

params:
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
